services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-todo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: login
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: todo
    ports:
      - 27017:27017
